backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: 'Upload media “{{path}}”'
    deleteMedia: 'Delete media “{{path}}”'

publish_mode: editorial_workflow
local_backend: true

media_folder: public/posts/media
public_folder: /posts/media

i18n:
  structure: multiple_files
  locales: [pt, en]
  default_locale: pt

collections:
  - name: posts
    label: Blog Posts
    label_singular: Post
    folder: public/posts
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    extension: md
    format: frontmatter
    identifier_field: slug
    preview_path: blog/{{slug}}
    summary: '{{title}} — {{date}}'
    sortable_fields: [date, title]
    media_folder: ''
    public_folder: ''
    i18n: true
    fields:
      - label: Slug
        name: slug
        widget: string
        hint: 'Usado para gerar a URL do post.'
        i18n: duplicate
        pattern:
          - '^[a-z0-9]+[a-z0-9-_]*$'
          - 'Use apenas letras minúsculas, números, hífen e underscore.'
      - label: Title
        name: title
        widget: string
        i18n: translate
      - label: Description
        name: description
        widget: text
        i18n: translate
      - label: Publish Date
        name: date
        widget: datetime
        format: 'MMMM D, YYYY'
        date_format: 'MMMM D, YYYY'
        time_format: false
        i18n: duplicate
      - label: Tags
        name: tags
        widget: list
        allow_add: true
        i18n: true
      - label: Body
        name: body
        widget: markdown
        i18n: translate
