backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: 'Upload media “{{path}}”'
    deleteMedia: 'Delete media “{{path}}”'

publish_mode: editorial_workflow
local_backend: true

media_folder: public/posts/media
public_folder: /posts/media

collections:
  - name: posts
    label: Blog Posts
    label_singular: Post
    folder: public/posts
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    extension: md
    format: frontmatter
    identifier_field: slug
    preview_path: blog/{{slug}}
    summary: '{{title}} — {{date}}'
    sortable_fields: [date, title]
    media_folder: ''
    public_folder: ''
    fields:
      - label: Slug
        name: slug
        widget: string
        hint: 'Use o formato yyyy-mm-dd-titulo-do-post.'
        pattern:
          - '^\d{4}-\d{2}-\d{2}-[a-z0-9]+(?:-[a-z0-9]+)*$'
          - 'Comece com a data (yyyy-mm-dd) seguida por um slug em minúsculas.'
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: text
      - label: Publish Date
        name: date
        widget: date
        format: 'YYYY-MM-DD'
      - label: Tags
        name: tags
        widget: list
        allow_add: true
      - label: Body
        name: body
        widget: markdown
