backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: 'Upload media “{{path}}”'
    deleteMedia: 'Delete media “{{path}}”'

publish_mode: editorial_workflow
local_backend: true

media_folder: public/posts/media
public_folder: /posts/media

i18n:
  structure: multiple_files
  locales: [pt, en]
  default_locale: pt

collections:
  - name: posts
    label: Blog Posts
    label_singular: Post
    folder: public/posts
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    extension: md
    format: frontmatter
    identifier_field: slug
    preview_path: blog/{{slug}}
    summary: '{{title}} — {{date}}'
    sortable_fields: [date, title]
    media_folder: ''
    public_folder: ''
    i18n: true
    fields:
      - label: Slug
        name: slug
        widget: string
        hint: 'Usado para gerar a URL e relacionar com a lista em posts.json.'
        i18n: duplicate
      - label: Title
        name: title
        widget: string
        i18n: translate
      - label: Description
        name: description
        widget: text
        i18n: translate
      - label: Publish Date
        name: date
        widget: datetime
        format: 'MMMM D, YYYY'
        date_format: 'MMMM D, YYYY'
        time_format: false
        i18n: duplicate
      - label: Tags
        name: tags
        widget: list
        allow_add: true
        i18n: true
      - label: Body
        name: body
        widget: markdown
        i18n: translate

  - name: posts_index
    label: Listagem do Blog
    delete: false
    editor:
      preview: false
    files:
      - label: Lista (Português)
        name: posts_pt
        file: public/posts/posts.json
        format: json
        fields:
          - label: Posts
            name: posts
            widget: list
            summary: '{{fields.title}}'
            fields:
              - { label: Slug, name: slug, widget: string }
              - { label: Título, name: title, widget: string }
              - { label: Data, name: date, widget: string }
              - { label: Descrição, name: description, widget: text }
              - label: Tags
                name: tags
                widget: list
                allow_add: true
      - label: Listing (English)
        name: posts_en
        file: public/posts/posts.en.json
        format: json
        fields:
          - label: Posts
            name: posts
            widget: list
            summary: '{{fields.title}}'
            fields:
              - { label: Slug, name: slug, widget: string }
              - { label: Title, name: title, widget: string }
              - { label: Date, name: date, widget: string }
              - { label: Description, name: description, widget: text }
              - label: Tags
                name: tags
                widget: list
                allow_add: true
