name: Auto PR to release when main changes

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  open-pr:
    runs-on: ubuntu-latest
    env:
      RELEASE_BRANCH: "release"
      BOT_NAME: "workflow-bot"
      BOT_EMAIL: "workflow-bot@users.noreply.github.com"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup git
        run: |
          git config user.name  "$BOT_NAME"
          git config user.email "$BOT_EMAIL"
          git fetch --all --prune

      - name: Install GitHub CLI
        uses: cli/cli@v2
        with:
          version: latest

      - name: Create/Update PR release <- main (no direct push)
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -e

          if ! git show-ref --verify --quiet "refs/remotes/origin/${RELEASE_BRANCH}"; then
            echo "Branch ${RELEASE_BRANCH} não existe. Saindo."
            exit 0
          fi

          # Se release já contém main, não precisa de PR
          git checkout "${RELEASE_BRANCH}"
          git fetch origin main --prune
          if git merge-base --is-ancestor origin/main HEAD; then
            echo "release já contém main. Nada a fazer."
            exit 0
          fi

          TMP="ci/update-${RELEASE_BRANCH}-from-main"
          git checkout -B "${TMP}" "origin/${RELEASE_BRANCH}"

          # Merge (sem reescrever histórico)
          if ! git merge --no-edit origin/main; then
            echo "Conflito ao mesclar main em release. Abortando tentativa."
            git merge --abort || true
            exit 0
          fi

          git push -u origin "${TMP}"

          TITLE="chore: update ${RELEASE_BRANCH} with latest main"
          BODY=$'Atualiza a branch '"\`${RELEASE_BRANCH}\`"' com a última main.\n\nPR aberta automaticamente pelo workflow.'

          # Reusa PR se já existir
          EXISTING=$(gh pr list --base "${RELEASE_BRANCH}" --head "${TMP}" --json number --jq '.[0].number' || true)
          if [ -n "$EXISTING" ]; then
            echo "PR #$EXISTING já existe. Atualizada com novo push."
          else
            gh pr create \
              --base "${RELEASE_BRANCH}" \
              --head "${TMP}" \
              --title "${TITLE}" \
              --body  "${BODY}" \
              --label "auto-update"
          fi

          # (Opcional) Auto-merge quando checks passarem:
          # gh pr merge "${TMP}" --auto --merge || true
