name: CI - PR checks

on:
  pull_request:
    branches: [ "release", "main" ]   # roda em PRs pra release e pra main
    paths-ignore:
      - "**/*.md"
      - ".vscode/**"
      - ".husky/**"

permissions:
  contents: read

jobs:
  quality:
    name: Lint • Typecheck • Test • Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Typecheck
        run: npm run typecheck --if-present

      - name: Tests
        run: npm test --if-present -- --run

      - name: Build
        run: npm run build
